name: online_bank
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  zoom_tap_animation: ^1.1.0
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  flutterfire_cli: ^1.0.0
  firebase_messaging: ^15.0.4
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

 